import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    <header className="bg-[#0A3255]">
      <div className="max-w-7xl mx-auto flex justify-between items-center p-3">
        <Link href="/" passHref>
          <div className="text-[#F8BE12] text-[26px] font-[400] font-bold">
            workable
          </div>

        </Link>
        

        <div className="flex items-center space-x-6 text-white">
        <div className="relative group">
          <a href="#" className="text-white px-4 py-2 inline-block">
            Job Portals
          </a>

          {/* Dropdown: sekarang nempel langsung ke bawah */}
          <div className="absolute left-0 top-full hidden group-hover:block bg-[#F8F7F3] text-[#0A3255] shadow-md rounded-md py-1 w-48 z-50">
            <Link href="resume-builder" passHref className="block px-4 py-2 hover:bg-gray-100">Resume Builder</Link>
            <Link href="job-listing" passHref className="block px-4 py-2 hover:bg-gray-100">Job Listings</Link>
          </div>
        </div>
        <div className="relative group">
          {/* Link utama */}
          <a href="#" className="text-white px-4 py-2 inline-block">
            Education
          </a>

          {/* Dropdown: sekarang nempel langsung ke bawah */}
          <div className="absolute left-0 top-full hidden group-hover:block bg-[#F8F7F3] text-[#0A3255] shadow-md rounded-md py-1 w-48 z-50">
            <Link href="scholarship" passHref className="block px-4 py-2 hover:bg-gray-100">Scholarships</Link>
            <Link href="education-listing" passHref className="block px-4 py-2 hover:bg-gray-100">Education Listings</Link>
          </div>
        </div>


         
          <Link href="community" passHref>
            <span className="text-white px-4 py-2 inline-block hover:underline">Community</span>
          </Link>

          <Link href="profile" passHref>
            <span className="text-white px-4 py-2 inline-block hover:underline">Profile</span>
          </Link>
          <Link href="login-page" passHref className="hover:underline">
            <button className="bg-[#F8BE12] text-blue-900 font-semibold px-6 py-2 rounded-[13px] hover:bg-yellow-300 transition-all duration-200">
              Login
            </button>
          </Link>
          
        </div>
      </div>
    </header>
        {children}
        <header className="bg-[#092A47]">
          <div className="max-w-7xl mx-auto flex justify-between items-center p-3">
            <div className="text-[#F8BE12] text-[26px] font-[400] font-bold">
              workable
            </div>

            
          </div>
        </header>

      </body>
    </html>
  );
}
